# Generated by Django 4.0 on 2024-11-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=15, unique=True, verbose_name='Immatriculation')),
                ('marque', models.CharField(max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle')),
                ('couleur', models.CharField(max_length=30, verbose_name='Couleur')),
                ('annee_fabrication', models.PositiveIntegerField(verbose_name='Année de fabrication')),
                ('proprietaire', models.CharField(max_length=100, verbose_name='Nom du propriétaire')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
